Warp-RNNT and Static/Dynamic build mode
rwth-i6/i6_native_ops pull request #2
Opened 2024-04-17 07:55 UTC by JackTemaki

Adds the Warp-RNNT implementation from https://github.com/1ytic/warp-rnnt

Supports building via setup.py but also dynamic loading via [torch.util.cpp_extensions.load](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.load)

2024-04-18 09:21 UTC, DanEnergetics reviewed
How does dynamic loading work now? My naive attempt does not work
```
>>> sys.path.insert(0, "/path/to/containing/folder")
>>> import i6_native_ops
[Works]
>>> import i6_native_ops.warp_rnnt as rnnt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'i6_native_ops.warp_rnnt'
```
Do I need to use `from torch.utils.cpp_extension import load` everytime I want to load it?

2024-04-18 09:21 UTC, DanEnergetics commented on i6_native_ops/warp_rnnt/__init__.py
> +                f"{base_path}/core.cu",
Is there a reason not to write:
```suggestion
                os.path.join(base_path, "core.cu"),
```
Also in the following, e.g. also `setup.py`.

2024-04-18 09:34 UTC, curufinwe requested changes
Some style comments for now. Will test if I can compile this next.

2024-04-18 09:34 UTC, curufinwe commented on i6_native_ops/warp_rnnt/__init__.py
> +    import i6_native_ops.warp_rnnt.warp_rnnt_core as core
Why not a relative import?

2024-04-18 09:34 UTC, curufinwe commented on i6_native_ops/warp_rnnt/__init__.py
> +
Please no empty lines at the beginning of new indentation (also in many other places throughout this file).

2024-04-18 09:34 UTC, curufinwe commented on i6_native_ops/warp_rnnt/__init__.py
> +              reduction: Literal['sum', 'mean', 'none'] = 'none',
An enum would be nicer here

2024-04-18 09:34 UTC, curufinwe commented on i6_native_ops/warp_rnnt/binding.cpp
> +
Also here empty lines

2024-04-18 09:34 UTC, curufinwe commented on i6_native_ops/warp_rnnt/__init__.py
> +
Way too many empty lines here

2024-04-18 09:39 UTC, JackTemaki commented
@curufinwe the code you commented on is the one copied from the original warp_rnnt repo without any modification. Do we really want to edit it?

2024-04-18 09:41 UTC, JackTemaki commented
> How does dynamic loading work now? My naive attempt does not work
> 
> ```
> >>> sys.path.insert(0, "/path/to/containing/folder")
> >>> import i6_native_ops
> [Works]
> >>> import i6_native_ops.warp_rnnt as rnnt
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'i6_native_ops.warp_rnnt'
> ```
> 
> Do I need to use `from torch.utils.cpp_extension import load` everytime I want to load it?

The repo now follows the python convention that the package is "within" the repo, so your path insert is probably wrong, it should be:
```sys.path.insert(0, "/path/to/containing/folder/i6_native_ops")```

2024-04-22 09:41 UTC, curufinwe commented
> @curufinwe the code you commented on is the one copied from the original warp_rnnt repo without any modification. Do we really want to edit it?

Fine, let's leave it alone to make updating with new code from upstream easier.

2024-04-22 10:12 UTC, curufinwe commented
It seems that now to get to the fbw op we need to do:
`from i6_native_ops.fbw.fbw_core import fbw`. @DanEnergetics Was this the case before aswell? If not we should make sure previously written import statements do not break.

2024-04-22 10:30 UTC, JackTemaki commented
> It seems that now to get to the fbw op we need to do: `from i6_native_ops.fbw.fbw_core import fbw`. @DanEnergetics Was this the case before aswell? If not we should make sure previously written import statements do not break.

This was not the case, I hope this can be fixed with a symlink. But I also recommend that you also put the PyTorch code for the op in the repo here before starting setups with the new syntax, for me it was surprising to see only the native code but not the torch wrapping code here.

2024-04-22 11:10 UTC, DanEnergetics commented
Yes, this would technically break some setups. However, it appears only in one line in the Sisyphus recipes so far so it would be easy to fix. Otherwise the `warp_rnnt` op and the `fbw` op compile for me so I would be okay with merging.

2024-04-22 14:08 UTC, JackTemaki commented
@DanEnergetics I added a symlink, can you check if the old import works like this?

2024-04-22 17:24 UTC, DanEnergetics commented
The symlink would probably only help the dynamic loading. Duplicating the CUDAExtension with a different name fixes it for me.

2024-04-23 09:23 UTC, JackTemaki commented
Ok then I remove the symlink!

2024-04-23 10:00 UTC, DanEnergetics approved these changes

2024-04-23 14:34 UTC, curufinwe commented
Do we need to fix this with code duplication? Couldn't we just add an `__init__.py` file and import the name from the new location? Also for the new location I would suggest creating a package `i6_native_ops.fbw` and importing the fbw function from `i6_native_ops.fbw.core`.

2024-04-24 08:31 UTC, DanEnergetics commented
> Do we need to fix this with code duplication?

We could, as you said, also make an `__init__.py` file that imports fbw. In order to guarantee that past imports still work, we would have to have this file in a nativeops folder though since the import before was `from nativeops import fbw`. So something like this
```
i6_native_ops
├── i6_native_ops
|   ├── warp_rnnt
|   ├── fbw
├── nativeops
    ├── __init__.py
```
And then just `from i6_native_ops.fbw.fbw_core import fbw` in the new `__init__.py`.
Again, I do not care about keeping the legacy import that much, because so far it was only me using it, I did not push any code to any other repo that contains this and there is only one line I would have to change overall.

> for the new location I would suggest creating a package i6_native_ops.fbw and importing the fbw function from i6_native_ops.fbw.core

This is reasonable but I could do this also in another PR, though. I wanted to add some python code to the fbw package.

2024-04-29 11:54 UTC, curufinwe commented
OK, I also talked to @JackTemaki offline about this and we agreed to skip backward compatibility. I have pushed the relevant changes + a new __init__.py for the fbw module. Are you two @DanEnergetics @JackTemaki OK with these changes?

2024-04-29 12:22 UTC, DanEnergetics commented
> a new init.py for the fbw module

I can't seem to see it. Otherwise I'm okay with the changes.

2024-04-29 15:30 UTC, JackTemaki commented
@curufinwe same as @DanEnergetics  I do not see the changes

2024-04-30 07:35 UTC, curufinwe commented
Ups, forgot to add the __init__.py file. Now it's as it should be.

2024-04-30 07:36 UTC, merged