Add monotonic_rnnt torch op
rwth-i6/i6_native_ops pull request #5
Opened 2024-07-04 10:42 UTC by SimBe195

Port of [https://github.com/SimBe195/monotonic-rnnt](https://github.com/SimBe195/monotonic-rnnt) to i6_native_ops. This was originally a fork of [https://github.com/HawkAaron/warp-transducer](https://github.com/HawkAaron/warp-transducer) with the main changes being:

- Changed to monotonic (RNA) label topology
- Using a packed input activation tensor and merged-in softmax operation for more memory efficiency
- Allowing the restriction of the alignment-path-grid to a region around a given target alignment
- Some general refactoring, test cases etc.

2024-08-13 16:31 UTC, DanEnergetics requested changes
Just a few small things. Otherwise, I ran it and it all works fine according to your tests. It's nice that you included numerical calculations in them.
Btw, do we need to include the license from the original repository like @JackTemaki did it for the warp_rnnt module?

2024-08-13 16:31 UTC, DanEnergetics commented on i6_native_ops/monotonic_rnnt/__init__.py
> +current_directory = os.path.dirname(current_file_path)
I don't think these two lines are used

2024-08-13 16:31 UTC, DanEnergetics commented on i6_native_ops/monotonic_rnnt/__init__.py
> +class MonotonicRNNTLoss(torch.nn.Module):
When does one need this as a torch.nn.Module? Would a definition as a function like above not be enough? This seems to just call `apply` method of the `MonotonicRNNTFunction`

2024-08-13 16:31 UTC, DanEnergetics commented on i6_native_ops/monotonic_rnnt/__init__.py
> +        assert core is not None
Would this ever be the case? Wouldn't `torch.utils.cpp_extension.load` just throw an error instead of returning `None`?

2024-08-13 16:31 UTC, DanEnergetics commented on i6_native_ops/monotonic_rnnt/__init__.py
> +                                       (T_1*(S_1+1) + T_2*(S_2+1) + ... + T_B*(S_B+1), V), where B is the minibatch index,
IMO this indentation makes it less readable and it's not standard I think

2024-09-11 15:00 UTC, curufinwe requested changes

2024-09-11 15:00 UTC, curufinwe commented on i6_native_ops/monotonic_rnnt/__init__.py
> +import os
Please add an `__all__` field.

2024-09-11 15:00 UTC, curufinwe commented on setup.py
> +            name="i6_native_ops.monotonic_rnnt.monotonic_rnnt_core",
rename to `i6_native_ops.monotonic_rnnt.core`

2024-10-07 11:39 UTC, SimBe195 commented
Implemented all the suggestions from @DanEnergetics and @curufinwe now. Thanks for the feedback!

2024-10-09 12:23 UTC, curufinwe commented
Sorry for the rename request. I forgot that this is the name of the .so file. Here it would be better to have individual names for each OP. I reverted this.

2024-10-09 12:23 UTC, curufinwe approved these changes

2024-10-09 12:56 UTC, DanEnergetics approved these changes
All looks good to me!

2024-10-09 13:11 UTC, JackTemaki approved these changes
I only did a quick check over the python interface, besides the kind of hard to understand input format of "acts" this seems fine.

2024-10-09 13:39 UTC, merged